sudo: required
services:
  - docker
before_install:
  - docker build -t strisen/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true strisen/react-test npm test
after_success:
  - docker build -t strisen/multi-client ./client
  - docker build -t strisen/multi-nginx ./nginx
  - docker build -t strisen/multi-server ./server
  - docker build -t strisen/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push strisen/multi-client
  - docker push strisen/multi-nginx
  - docker push strisen/multi-server
  - docker push strisen/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-631434563677"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
